// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtmypbvdyibrxzcxhemp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bXlwYnZkeWlicnh6Y3hoZW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODE1OTIsImV4cCI6MjA2MzA1NzU5Mn0.pPuqbCYcEJzNDCaupTWoMSkdR6QaxfHyTMWOM1E-Z7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);